# Configuration file for syncing template files from TemplateBase repository
# This file should be placed in the root of repositories that want to sync templates
# 
# Example usage:
# - Place this file in your repository root
# - The GitHub Actions workflow will automatically detect it and sync the specified items
# - Items can be files or directories
# - Directories will be synced recursively

items:
  # VS Code configuration files
  - .vscode/settings.json
  - .vscode/tasks.json
  - .vscode/launch.json
  
  # Core utility files
  - DatabaseUtilities/
  - LoggingUtilities/
  - ServerUtilities/
  - GeneralUtilities/
  - GenerationUtilities/
  
  # Website utilities
  - website/
  
  # Project configuration files
  - .gitignore
  - Project.csproj
  - tsconfig.json

# Optional: Specify which branch to sync from (defaults to main)
# source_branch: main

# Optional: Specify which branch to sync to (defaults to main)
# target_branch: main

# Optional: Exclude specific files or patterns from syncing
# exclude:
#   - "**/*.log"
#   - "**/node_modules/**"
#   - "**/.env*"
